project:
  type: website

website:
  open-graph: true
  title: "Cloud-Native Geospatial at LPS 2025"
  site-url: https://vorgeo.github.io/lps25-cng/
  image: "images/cng_perfect_loop.gif"
  navbar:
    title: "Cloud-Native Geospatial at LPS 2025"
    logo: "images/cng_perfect_loop.gif"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/VorGeo/lps25-cng
          - text: Report a Bug
            href:  https://github.com/VorGeo/lps25-cng/issues

format:
  html:
    theme:
      light: sketchy
      dark: darkly
    # css: styles.css
    toc: true
